### ISSUE TITLE
ptr type field not work as expected

### ISSUE THREAD

**Issue by yinheli** [gookit/validate#64]
```go
// Test_validate_with_point 
// failed
//  Note: ptr field name expected works, but not actually
func Test_validate_with_point(t *testing.T) {
	type Foo struct {
		Name *string `validate:"in:henry,jim"`
	}
	name := "henry"
	valid := validate.New(&Foo{Name: &name})
	if !valid.Validate() {
		t.Log("err:", valid.Errors)
	}
}

// Test_validate_without_point 
// this tests will pass
func Test_validate_without_point(t *testing.T) {
	type Foo struct {
		Name string `validate:"in:henry,jim"`
	}
	name := "henry"
	valid := validate.New(&Foo{Name: name})
	if !valid.Validate() {
		t.Log("err:", valid.Errors)
	}
}
```

**Comment by fishyww** [comment]
@inhere Has this problem been solved? If not, please assign to me

**Comment by inhere** [comment]
@fishyww  I will fix it today

**Comment by fishyww** [comment]
@inhere Sorry~ I only saw the information after completing the PR.

**Comment by inhere** [comment]
@yinheli  hi, has been fixed by @fishyww 👍

**Comment by yinheli** [comment]
Thanks!, Well done. 👍

**Comment by SharkFourSix** [comment]
Still facing this issue with filters: trim and lower. They seem to be expecting non-pointer values.

What is the best way to validate and filter pointer types? @inhere @fishyww
